version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "[maven] "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
