name: Manual Release

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow: maven.yaml
          workflow_conclusion: success
          name: automated-modlist-installer
      - name: Display structure of downloaded files
        run: ls -R
