name: Manual Release

on:
  workflow_dispatch:

jobs:
  pack:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: maven.yaml
          workflow_conclusion: success
          name: automated-modlist-installer
          path: artifact
      - name: Copy executable
        run: mkdir release && cp -p artifact/*.exe release
      - name: Copy resources
        run: cp -a data/ release && cp -a locales/ release && cp -a resources/ release
      - name: Display structure of downloaded files
        run: ls -R release/
