name: Manual Release

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: automated-modlist-installer
          github-token: ${{ secrets.GH_PAT }}
          repository: Tosox/Automated-Modlist-Installer
          run-id: 7829083020
      - name: Display structure of downloaded files
        run: ls -R
