name: Manual Release

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Workflow Run ID
        id: get_workflow_run_id
        run: |
          # Script to get the latest successful workflow run ID of a specific workflow
          RUN_ID=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/maven.yaml/runs?status=success&per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "::set-output name=run_id::${RUN_ID}"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: automated-modlist-installer
          github-token: ${{ secrets.GH_PAT }}
          repository: Tosox/Automated-Modlist-Installer
          run-id: ${{ steps.get_workflow_run_id.outputs.run_id }}
      - name: Display structure of downloaded files
        run: ls -R
