name: CI Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0
jobs:
  build:
    uses: ./.github/workflows/maven.yml
  release:
    permissions: write-all
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: maven.yaml
          workflow_conclusion: success
          name: stalker-modlist-installer
          path: artifact
      - name: Copy executable
        run: mkdir release && cp -p artifact/*.exe release
      - name: Copy resources
        run: cp -a data/ release && cp -a locales/ release && cp -a resources/ release
      - name: Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: STALKER-Modlist-Installer-${{ github.event.inputs.build-ver }}.zip
          directory: release/
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.build-ver }}
          release_name: S.T.A.L.K.E.R. Modlist Installer ${{ github.event.inputs.build-ver }}
          body_path: ./CHANGELOG.md
          prerelease: false
      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/STALKER-Modlist-Installer-${{ github.event.inputs.build-ver }}.zip
          asset_name: STALKER-Modlist-Installer-${{ github.event.inputs.build-ver }}.zip
          asset_content_type: application/zip
